### ISSUE TITLE
albacore compatibility

### ISSUE THREAD

**Issue by clarepacini** [mitenjain/signalAlign#4]
Hi, 
I have used albacore version 2.1.3 however, signalAlign says it can't find the version used in my data. Any suggestions on how to fix this? Thanks, Clare

~/signalAlign/bin$ ./runSignalAlign --debug -d /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0 -r /mnt/cep46/sacCer3.fa -o /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/SignalAlign -x adenosine -f full
Command Line: ./runSignalAlign --debug -d /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0 -r /mnt/cep46/sacCer3.fa -o /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/SignalAlign -x adenosine -f full

#   Starting Signal Align
#   Aligning files from: /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0
#   Aligning to reference: /mnt/cep46/sacCer3.fa
#   Aligning maximum of 500 files
#   Using model: threeState
#   Using banding: True
#   Aligning to regions in: None
#   Non-default template HMM: None
#   Non-default complement HMM: None
#   Template HDP: None
#   Complement HDP: None
    
signalAlign - indexing reference
signalAlign - indexing reference, done
[runSignalAlign]:NOTICE: Got 500 files to align
/mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0/dhcp_10_248_145_211_eduroam_wireless_private_cam_ac_uk_20180118_FAH57246_MN24473_sequencing_run_YeastGenomic_80750_read_4_ch_3_strand.fast5
[SignalAlignment.run]INFO: Starting on /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0/dhcp_10_248_145_211_eduroam_wireless_private_cam_ac_uk_20180118_FAH57246_MN24473_sequencing_run_YeastGenomic_80750_read_4_ch_3_strand.fast5
[NanoporeRead:_initialize]ERROR /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH57246_YeastGenomic/workspace/pass/barcode02/0/dhcp_10_248_145_211_eduroam_wireless_private_cam_ac_uk_20180118_FAH57246_MN24473_sequencing_run_YeastGenomic_80750_read_4_ch_3_strand.fast5 missing version
Traceback (most recent call last):
  File "./runSignalAlign", line 234, in <module>
    sys.exit(main(sys.argv))
  File "./runSignalAlign", line 215, in main
    alignment.run()
  File "/home/cep46/signalAlign/src/signalalign/signalAlignment.py", line 80, in run
    ok      = npRead.Write(parent_job=None, out_file=fH, initialize=True)
  File "/home/cep46/signalAlign/src/signalalign/nanoporeRead.py", line 435, in Write
    self.close()
  File "/home/cep46/signalAlign/src/signalalign/nanoporeRead.py", line 548, in close
    self.fastFive.close()
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.7.0rc2-py2.7-linux-x86_64.egg/h5py/_hl/files.py", line 287, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/easy_install-7yiMj9/h5py-2.7.0rc2/h5py/_objects.c:2578)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/easy_install-7yiMj9/h5py-2.7.0rc2/h5py/_objects.c:2537)
  File "h5py/h5f.pyx", line 230, in h5py.h5f.get_obj_ids (/tmp/easy_install-7yiMj9/h5py-2.7.0rc2/h5py/h5f.c:3179)
ValueError: Not a file id (Not a file id)

**Comment by mitenjain** [comment]
Hello,

Sorry for the hassle. Are you using a virtualenv for signalAlign's Python dependencies? 

-Miten

**Comment by clarepacini** [comment]
Hi Miten,
Thanks for gettting back to me. We did try the virtualenv but were unsuccessful. In the end we managed to update the h5py libraries etc and have run one test signalAlign with output! 
Clare
